### ISSUE TITLE
GET all tools

### ISSUE THREAD

**Issue by WeiMingTay** [WeiMingTay/capstone-verleihApp#10]
**As a User** 
**I need** to view a list of all tools
**to be able to** have a comprehensive overview of my entire list.

## Description
Implement a feature that allows users to retrieve and view a list of all their movies from the backend.

## Acceptance Criteria

- [x] Create a GET "/api/movies" endpoint to fetch all movies from the backend.
- [ ] Display the list of all movies on the starting page of the frontend.

## Tasks

(for developers team)

- [x] Create a Model with "Id, title and author"
- [ ] Create a "View All movies" component in the UI.
- [ ] Implement a GET request to retrieve all movies from the backend.
- [ ] Update the frontend to display the list of movies.
- [ ] Implement Unit and Integration Test.
- [ ] add some styling
