### ISSUE TITLE
DELETE own tool

### ISSUE THREAD

**Issue by WeiMingTay** [WeiMingTay/capstone-verleihApp#18]
**As a User**
**I need** to delete a movie from my favourites library

#### Description
Implement a feature that allows users to delete a movie from their library. Users should be able to remove a book they no longer wish to keep in their collection.

#### Acceptance Criteria

- [ ] Create a DELETE Endpoint "/api/movies/{id}" which deletes the movie specified by the id.
- [ ] On the Details-Page of each movie should be a "delete" Button.
- [ ] When clicking on the "Delete" button, the movie should be removed from the database.

#### Tasks

- [ ] Add a "Delete" button for each movie in the UI.
- [ ] Create a DELETE request or endpoint to remove the movie from the backend.
- [ ] Implement Unit and Integration Test.
