### ISSUE TITLE
Add (POST) Tool

### ISSUE THREAD

**Issue by WeiMingTay** [WeiMingTay/capstone-verleihApp#3]
**As a User** 
**I need to** add a new tool to the database
**to be able to** keep track of new tools I

## Description
Implement a feature that allows users to add a new tools to the databse. Users should be able to enter tool details such as:
- name
- categorie[]
- upload image
- description
- step-by-step anleitung
- author(automatisch)

## Acceptance Criteria

- [x] Create a POST endpoint "/api/tools" to add a new tool to the backend.
- [x] The the Route "/tools/add" should display the form, for the user to add a tool.
- [x] Ensure that the added tool appears in the list of tools -> mongoDB.

## Tasks

- [x] Create a "Werkzeug hinzufügen" button in the UI.
- [x] Implement a form to input tool details.
- [x] Create a POST request to send data to the backend.
- [x] Implement Unit and Integration Test.
- [x] add some styling
